### ISSUE TITLE
Files missing from NetworkTables.core project

### ISSUE THREAD

**Issue by sipsorcery** [robotdotnet/NetworkTables#45]
'F:\Dev\FrcSmartDashboard\RdnNetworkTables\src\FRC.NetworkTables.Core\Native\Uname.cs' could not be found.	
'F:\Dev\FrcSmartDashboard\RdnNetworkTables\src\FRC.NetworkTables.Core\Native\LoaderUtilities.cs' could not be found.	
'F:\Dev\FrcSmartDashboard\RdnNetworkTables\src\FRC.NetworkTables.Core\Native\LibraryLoader.cs' could not be found.

**Comment by ThadHouse** [comment]
I'm not maintaining the old project structure anymore. You need to use the .NET Core standalone tooling or VS 2015 with the .NET Core preview tooling in order to build the project. Those use the .xproj solution and the .xproj files in each project if building using visual studio. I'll delete the old projects soon.
